name: Canada Relocation Job Alert
on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch: {}  # Manual trigger
  push:
    branches: [ main, master ]

jobs:
  job-alert:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Create database directory
        run: mkdir -p db
        
      - name: Run job alert
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          TARGET_EMAIL: ${{ secrets.TARGET_EMAIL }}
          MIN_MATCH_SCORE: ${{ secrets.MIN_MATCH_SCORE || '70' }}
          REQUEST_TIMEOUT: ${{ secrets.REQUEST_TIMEOUT || '10' }}
          REQUEST_DELAY: ${{ secrets.REQUEST_DELAY || '1.0' }}
          MAX_JOBS_PER_SOURCE: ${{ secrets.MAX_JOBS_PER_SOURCE || '5' }}
        run: python worker.py
        
      - name: Upload database as artifact (for debugging)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: job-database
          path: db/
          retention-days: 7
          
      - name: Notify on failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          channel: '#job-alerts'
          text: 'Job alert workflow failed - check the logs for details'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
